# Generated by Django 6.0.3 on 2026-03-28 02:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('user_name', models.CharField(default='System', max_length=200)),
                ('urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('Advisory', 'Advisory'), ('Warning', 'Warning'), ('Danger', 'Danger'), ('Resolved', 'Resolved')], default='Advisory', max_length=20)),
                ('zone', models.CharField(default='All Zones', max_length=100)),
                ('channel', models.CharField(default='Web', max_length=50)),
                ('sent_by', models.CharField(default='Admin', max_length=200)),
                ('recipients_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvacCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('zone', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('capacity', models.IntegerField(default=0)),
                ('occupancy', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Full', 'Full'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('facilities_available', models.JSONField(blank=True, default=list)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('contact', models.CharField(blank=True, default='', max_length=50)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evac_centers',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Flood', 'Flood'), ('Fire', 'Fire'), ('Earthquake', 'Earthquake'), ('Landslide', 'Landslide'), ('Storm', 'Storm')], max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('location', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Responded', 'Responded'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('reporter', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(default='web', max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('zone', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('household_members', models.IntegerField(default=1)),
                ('contact', models.CharField(blank=True, default='', max_length=50)),
                ('evacuation_status', models.CharField(choices=[('Safe', 'Safe'), ('Evacuated', 'Evacuated'), ('Unaccounted', 'Unaccounted')], default='Safe', max_length=20)),
                ('vulnerability_tags', models.JSONField(blank=True, default=list)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('added_by', models.CharField(default='Mobile', max_length=200)),
                ('source', models.CharField(default='mobile', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'residents',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_users',
                'ordering': ['-created_at'],
            },
        ),
    ]
